# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ed5283da6345ed8cf3705909359022109594f6f2f181c5a22fc29c5be23bab74b788cf149a3949b3e281f5e06e5d4966682debdbcf0c2301c566e1866a01d8

test:
  secret_key_base: 64b33100aa7599c78bf04c2de539bc6da851656fc9b9ea7298af6b24dd49dd794bcb93d9d86ad3d8bc593c8236de98e39965a87d45bf256f4fc3f25cea20d354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
